config:
  clientID: "otus-service-user"
  clientSecret: "tlDTc1VyLLdXcsreWKSUUlmCg67gUcIh"
  cookieSecret: "azNlbzBFZ1dSMWZHT1c3bkVPNXBKaXA0WGtNSXdYdUk="
  cookieName: "otus-auth"
  configFile: |
    reverse_proxy = true
    code_challenge_method = "S256"
    provider = "keycloak-oidc"
    redirect_url = "http://arch.homework/oauth2/callback"
    oidc_issuer_url = "http://keycloak.security/realms/otus"
    insecure_oidc_skip_issuer_verification = true
    email_domains = [ "*" ]
    cookie_secure = false
    silence_ping_logging = true
    set_authorization_header = true
    skip_jwt_bearer_tokens = true
sessionStorage:
  type: redis
redis:
  enabled: true
ingress:
  enabled: true
  className: nginx
  path: /oauth2
  hosts:
    - arch.homework