auth:
  adminUser: admin
  adminPassword: NIMDA
service:
  type: NodePort
ingress:
  enabled: true
  ingressClassName: nginx
  hostname: keycloak.arch.homework
  pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"