---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: otus-product
  name: postgresql-data
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/volume"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: otus-product
  name: postgresql-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi